# Generated by Django 4.2.11 on 2024-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0003_remove_applicatie_applicatie_gebruiker_naam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="taaktype_aanmaken_formulier_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
