# Generated by Django 4.2.11 on 2024-08-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0004_applicatie_taaktype_aanmaken_formulier_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="cache_timeout",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
