# Generated by Django 3.2.18 on 2024-05-22 08:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicaties", "0002_applicatie_valide_basis_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taaktype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("taakapplicatie_taaktype_url", models.URLField()),
                ("omschrijving", models.CharField(max_length=200)),
                (
                    "taakapplicatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taaktypes_voor_applicatie",
                        to="applicaties.applicatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taaktype",
                "verbose_name_plural": "Taaktypes",
                "ordering": ("omschrijving",),
            },
        ),
    ]
