# Generated by Django 3.2.18 on 2024-05-27 15:24

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Afdeling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("naam", models.CharField(max_length=100)),
                (
                    "onderdeel",
                    models.CharField(
                        choices=[
                            ("schoon", "Schoon"),
                            ("heel", "Heel"),
                            ("veilig", "Veilig"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaaktypeMiddel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("naam", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taaktype",
            name="actief",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="additionele_informatie",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="gerelateerde_onderwerpen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="gerelateerde_taaktypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="gerelateerde_taaktypes_voor_taaktype",
                to="taaktypes.Taaktype",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="icoon",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="taaktype/icons"
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="toelichting",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="verantwoordelijke",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="volgende_taaktypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="vorige_taaktypes_voor_taaktype",
                to="taaktypes.Taaktype",
            ),
        ),
        migrations.CreateModel(
            name="TaaktypeVoorbeeldsituatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "toelichting",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("waarom_wel", "Waarom wel"),
                            ("waarom_niet", "Waarom niet"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "taaktype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voorbeeldsituatie_voor_taaktype",
                        to="taaktypes.taaktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taaktype",
            name="afdelingen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_afdelingen",
                to="taaktypes.Afdeling",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="taaktypemiddelen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taaktypes_voor_taaktypemiddelen",
                to="taaktypes.TaaktypeMiddel",
            ),
        ),
    ]
