# Generated by Django 4.2.11 on 2024-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0002_auto_20240527_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="taakapplicatie_taaktype_url",
            field=models.URLField(unique=True),
        ),
    ]
