# Generated by Django 4.2.11 on 2024-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0004_taaktype_taakapplicatie_taaktype_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="afdeling",
            name="icoon",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="afdeling/icons"
            ),
        ),
    ]
