# Generated by Django 4.2.11 on 2024-06-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0005_afdeling_icoon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taaktype",
            name="verantwoordelijke",
        ),
        migrations.AddField(
            model_name="taaktype",
            name="verantwoordelijke_afdeling",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verantwoordelijke_afdeling_taaktypes",
                to="taaktypes.afdeling",
            ),
        ),
        migrations.AlterField(
            model_name="afdeling",
            name="onderdeel",
            field=models.CharField(
                blank=True,
                choices=[("schoon", "Schoon"), ("heel", "Heel"), ("veilig", "Veilig")],
                max_length=50,
                null=True,
            ),
        ),
    ]
