# Generated by Django 4.2.11 on 2024-08-06 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0006_remove_taaktype_verantwoordelijke_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taaktype",
            name="taakapplicatie_taaktype_uuid",
        ),
    ]
