# Generated by Django 4.2.11 on 2024-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0007_remove_taaktype_taakapplicatie_taaktype_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="toelichting",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
