# Generated by Django 4.2.15 on 2025-01-08 16:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0008_alter_taaktype_toelichting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("toon_in_planr", models.BooleanField(default=True)),
                ("toon_in_taakapplicatie", models.BooleanField(default=True)),
                ("open_in_nieuwe_tab", models.BooleanField(default=False)),
                ("url", models.URLField()),
                ("titel", models.CharField(max_length=100)),
                (
                    "taaktype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_voor_taaktype",
                        to="taaktypes.taaktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
