# Generated by Django 4.2.15 on 2025-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0010_taaktype_doorlooptijd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taaktype",
            name="doorlooptijd",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
