# Generated by Django 4.2.15 on 2025-11-10 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0011_alter_taaktype_doorlooptijd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taaktype",
            old_name="verantwoordelijke_persoon_naam",
            new_name="proceseigenaar_persoon_naam",
        ),
        migrations.RenameField(
            model_name="taaktype",
            old_name="verantwoordelijke_persoon_personeelsnummer",
            new_name="proceseigenaar_persoon_personeelsnummer",
        ),
    ]
