# Generated by Django 4.2.15 on 2025-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taaktypes", "0012_remove_taaktype_verantwoordelijke_persoon_naam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taaktype",
            name="procesregiseur_persoon_naam",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Naam procesregiseur",
            ),
        ),
        migrations.AddField(
            model_name="taaktype",
            name="procesregiseur_persoon_personeelsnummer",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Personeelsnummer procesregiseur",
            ),
        ),
        migrations.AlterField(
            model_name="taaktype",
            name="proceseigenaar_persoon_naam",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Naam proceseigenaar",
            ),
        ),
        migrations.AlterField(
            model_name="taaktype",
            name="proceseigenaar_persoon_personeelsnummer",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Personeelsnummer proceseigenaar",
            ),
        ),
    ]
