VERTALINGEN = {
    "status_wijziging": "Status wijziging",
    "melding_aangemaakt": "Melding aangemaakt",
    "taakopdracht_aangemaakt": "Taakopdracht aangemaakt",
    "taakopdracht_status_wijziging": "Taakopdracht status wijziging",
    "opgelost": "Opgelost",
    "niet_opgelost": "Niet opgelost",
    "niet_gevonden": "Niets aangetroffen",
    "aangemaakt": "Aangemaakt",
    "gewijzigd": "Gewijzigd",
    "verwijderd": "Verwijderd",
    "in_behandeling": "In behandeling",
    "openstaand": "Openstaand",
    "controle": "Controle",
    "afgehandeld": "Afgehandeld",
    "geannuleerd": "Geannuleerd",
    "nieuw": "Nieuw",
    "bezig": "Bezig",
    "voltooid": "Voltooid",
    "toegewezen": "Toegewezen",
    "adres": "Ter hoogte van",
    "lichtmast": "Lichtmast",
    "graf": "Graf",
    "vak": "Vak",
    "fotos": "Foto's",
    "aannemer": "Aangenomen door",
    "no_email": "De melder beschikt niet over een e-mailadres.",
    "grafnummer": "Grafnummer",
    "naam_melder": "Naam",
    "toelichting": "Toelichting",
    "email_melder": "E-mailadres",
    "begraafplaats": "Begraafplaats",
    "rechthebbende": "Is deze persoon de rechthebbende of belanghebbende?",
    "specifiek_graf": "Betreft het verzoek een specifiek graf?",
    "naam_overledene": "Naam overledene",
    "telefoon_melder": "Telefoonnummer",
    "terugkoppeling_gewenst": "Is terugkoppeling gewenst?",
    "wachten_melder": "Wachten melder",
    "pauze": "Pauze",
    "standaard": "Opmerking/foto toegevoegd",
    "signaal_toegevoegd": "Samengevoegd",
    "urgentie_aangepast": "Spoed aangepast",
    "melding_heropend": "Heropend",
}

MSB_WIJKEN = [
    {
        "code": "26",
        "omschrijving": "Bedrijventerrein Schieveen",
        "buurten": [{"code": "50", "omschrijving": "Bedrijventerrein Schieveen"}],
    },
    {
        "code": "23",
        "omschrijving": "Botlek-Europoort-Maasvlakte",
        "buurten": [
            {"code": "6", "omschrijving": "Botlek"},
            {"code": "7", "omschrijving": "Europoort"},
            {"code": "8", "omschrijving": "Maasvlakte"},
        ],
    },
    {
        "code": "15",
        "omschrijving": "Charlois",
        "buurten": [
            {"code": "72", "omschrijving": "Carnisse"},
            {"code": "70", "omschrijving": "Charlois Zuidrand"},
            {"code": "93", "omschrijving": "Heijplaat"},
            {"code": "74", "omschrijving": "Oud Charlois"},
            {"code": "77", "omschrijving": "Pendrecht"},
            {"code": "71", "omschrijving": "Tarwewijk"},
            {"code": "75", "omschrijving": "Wielewaal"},
            {"code": "78", "omschrijving": "Zuiderpark"},
            {"code": "76", "omschrijving": "Zuidplein"},
            {"code": "73", "omschrijving": "Zuidwijk"},
        ],
    },
    {
        "code": "3",
        "omschrijving": "Delfshaven",
        "buurten": [
            {"code": "21", "omschrijving": "Bospolder"},
            {"code": "20", "omschrijving": "Delfshaven"},
            {"code": "25", "omschrijving": "Middelland"},
            {"code": "24", "omschrijving": "Nieuwe Westen"},
            {"code": "27", "omschrijving": "Oud Mathenesse"},
            {"code": "29", "omschrijving": "Schiemond"},
            {"code": "23", "omschrijving": "Spangen"},
            {"code": "22", "omschrijving": "Tussendijken"},
            {"code": "28", "omschrijving": "Witte Dorp"},
        ],
    },
    {
        "code": "10",
        "omschrijving": "Feijenoord",
        "buurten": [
            {"code": "86", "omschrijving": "Afrikaanderwijk"},
            {"code": "81", "omschrijving": "Bloemhof"},
            {"code": "87", "omschrijving": "Feijenoord"},
            {"code": "82", "omschrijving": "Hillesluis"},
            {"code": "85", "omschrijving": "Katendrecht"},
            {"code": "17", "omschrijving": "Kop van Zuid"},
            {"code": "79", "omschrijving": "Kop van Zuid - Entrepot"},
            {"code": "88", "omschrijving": "Noordereiland"},
            {"code": "80", "omschrijving": "Vreewijk"},
        ],
    },
    {
        "code": "6",
        "omschrijving": "Hillegersberg-Schiebroek",
        "buurten": [
            {"code": "62", "omschrijving": "Hillegersberg Noord"},
            {"code": "61", "omschrijving": "Hillegersberg Zuid"},
            {"code": "65", "omschrijving": "Molenlaankwartier"},
            {"code": "60", "omschrijving": "Schiebroek"},
            {"code": "64", "omschrijving": "Terbregge"},
        ],
    },
    {
        "code": "17",
        "omschrijving": "Hoek van Holland",
        "buurten": [
            {"code": "2", "omschrijving": "Dorp"},
            {"code": "3", "omschrijving": "Rijnpoort"},
            {"code": "1", "omschrijving": "Strand en Duin"},
        ],
    },
    {
        "code": "16",
        "omschrijving": "Hoogvliet",
        "buurten": [
            {"code": "92", "omschrijving": "Hoogvliet Noord"},
            {"code": "99", "omschrijving": "Hoogvliet Zuid"},
        ],
    },
    {
        "code": "12",
        "omschrijving": "IJsselmonde",
        "buurten": [
            {"code": "90", "omschrijving": "Beverwaard"},
            {"code": "89", "omschrijving": "Groot IJsselmonde"},
            {"code": "84", "omschrijving": "Lombardijen"},
            {"code": "83", "omschrijving": "Oud IJsselmonde"},
        ],
    },
    {
        "code": "8",
        "omschrijving": "Kralingen-Crooswijk",
        "buurten": [
            {"code": "45", "omschrijving": "De Esch"},
            {"code": "42", "omschrijving": "Kralingen Oost"},
            {"code": "41", "omschrijving": "Kralingen West"},
            {"code": "43", "omschrijving": "Kralingse Bos"},
            {"code": "36", "omschrijving": "Nieuw Crooswijk"},
            {"code": "37", "omschrijving": "Oud Crooswijk"},
            {"code": "14", "omschrijving": "Rubroek"},
            {"code": "47", "omschrijving": "Struisenburg"},
        ],
    },
    {
        "code": "19",
        "omschrijving": "Nieuw Mathenesse",
        "buurten": [{"code": "26", "omschrijving": "Nieuw Mathenesse"}],
    },
    {
        "code": "5",
        "omschrijving": "Noord",
        "buurten": [
            {"code": "15", "omschrijving": "Agniesebuurt"},
            {"code": "31", "omschrijving": "Bergpolder"},
            {"code": "32", "omschrijving": "Blijdorp"},
            {"code": "58", "omschrijving": "Blijdorpsepolder"},
            {"code": "34", "omschrijving": "Liskwartier"},
            {"code": "35", "omschrijving": "Oude Noorden"},
            {"code": "16", "omschrijving": "Provenierswijk"},
        ],
    },
    {
        "code": "4",
        "omschrijving": "Overschie",
        "buurten": [
            {"code": "51", "omschrijving": "Kleinpolder"},
            {"code": "57", "omschrijving": "Landzicht"},
            {"code": "52", "omschrijving": "Noord Kethel"},
            {"code": "56", "omschrijving": "Overschie"},
            {"code": "54", "omschrijving": "Schieveen"},
            {"code": "55", "omschrijving": "Zestienhoven"},
        ],
    },
    {
        "code": "13",
        "omschrijving": "Pernis",
        "buurten": [{"code": "91", "omschrijving": "Pernis"}],
    },
    {
        "code": "14",
        "omschrijving": "Prins Alexander",
        "buurten": [
            {"code": "49", "omschrijving": "Het Lage Land"},
            {"code": "46", "omschrijving": "Kralingseveer"},
            {"code": "68", "omschrijving": "Nesselande"},
            {"code": "63", "omschrijving": "Ommoord"},
            {"code": "67", "omschrijving": "Oosterflank"},
            {"code": "48", "omschrijving": "Prinsenland"},
            {"code": "44", "omschrijving": "'s-Gravenland"},
            {"code": "66", "omschrijving": "Zevenkamp"},
        ],
    },
    {
        "code": "25",
        "omschrijving": "Rivium",
        "buurten": [{"code": "40", "omschrijving": "Rivium"}],
    },
    {
        "code": "1",
        "omschrijving": "Rotterdam Centrum",
        "buurten": [
            {"code": "12", "omschrijving": "Cool"},
            {"code": "13", "omschrijving": "Cs Kwartier"},
            {"code": "19", "omschrijving": "Dijkzigt"},
            {"code": "18", "omschrijving": "Nieuwe Werk"},
            {"code": "11", "omschrijving": "Oude Westen"},
            {"code": "10", "omschrijving": "Stadsdriehoek"},
        ],
    },
    {
        "code": "24",
        "omschrijving": "Rotterdam-Noord-West",
        "buurten": [{"code": "59", "omschrijving": "Bedrijvenpark Noord-West"}],
    },
    {
        "code": "27",
        "omschrijving": "Rozenburg",
        "buurten": [
            {"code": "5", "omschrijving": "Noordzeeweg"},
            {"code": "4", "omschrijving": "Rozenburg"},
        ],
    },
    {
        "code": "18",
        "omschrijving": "Spaanse Polder",
        "buurten": [{"code": "53", "omschrijving": "Spaanse Polder"}],
    },
    {
        "code": "22",
        "omschrijving": "Vondelingenplaat",
        "buurten": [{"code": "95", "omschrijving": "Vondelingenplaat"}],
    },
    {
        "code": "21",
        "omschrijving": "Waalhaven-Eemhaven",
        "buurten": [
            {"code": "96", "omschrijving": "Eemhaven"},
            {"code": "94", "omschrijving": "Waalhaven"},
            {"code": "98", "omschrijving": "Waalhaven Zuid"},
        ],
    },
]
