# Generated by Django 4.2.11 on 2024-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticatie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruiker",
            name="telefoonnummer",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
